### ISSUE TITLE
client class - skinport import

### ISSUE THREAD

**Issue by peterwal** [Nasus20202/skinport-bot#1]
Hello,

I feel like the skinport class with the client class is missing.
Would you be able to share that, please?

thank you, Peter

**Comment by Nasus20202** [comment]
The skinport package including skinport.Client is a part of the [skinport.py](https://pypi.org/project/skinport.py/) package. Are you sure you installed all project dependencies from [requirements.txt](https://github.com/Nasus20202/skinport-bot/blob/main/requirements.txt)? (pip install -r requirements.txt) 
If that's not the case, I will look into this problem later.

**Comment by peterwal** [comment]
my mistake. I had not installed "skinport.py" correctly, I downloaded the source and it is running fine now in PyCharm.
thank you
